export interface ThemeColors {
  /** Action color for buttons, links, and active states. @defaultValue `#1355ff` */
  action?: string;
  /** Hover color for action elements. @defaultValue `#0f44cc` */
  actionHover?: string;
  /** Text color shown on action-colored elements. @defaultValue `#ffffff` */
  actionText?: string;
  /** Shared background for UI surfaces such as panels, cards, and dropdowns. @defaultValue `#ffffff` */
  bg?: string;
  /** Background for hovered controls. @defaultValue `#dbdbdb` */
  hoverBg?: string;
  /** Background for active and pressed controls. @defaultValue `#c8d0d8` */
  activeBg?: string;
  /** Background for disabled controls. @defaultValue `#f5f5f5` */
  disabledBg?: string;
  /** Primary UI text color. @defaultValue `#47484a` */
  text?: string;
  /** Secondary UI text color. @defaultValue `#666666` */
  textMuted?: string;
  /** Text color for disabled controls. @defaultValue `#ababab` */
  textDisabled?: string;
  /** Shared UI border color. @defaultValue `#dbdbdb` */
  border?: string;
}

/** SuperDoc CSS variable overrides applied after the semantic theme values. */
export type ThemeVariableOverrides = {
  readonly [name: `--sd-${string}`]: string | null | undefined;
};

export interface ThemeConfig {
  /** Name used in the generated class, such as `product` for `sd-theme-product`. */
  name?: string;
  /**
   * Font family for SuperDoc UI surfaces that inherit the theme, such as body-mounted dialogs
   * and floating surfaces. The Editor root and the external toolbar set `--sd-ui-font-family`
   * inline from `uiDisplayFallbackFont`, and an inline declaration outranks the theme class —
   * set `uiDisplayFallbackFont` to the same value to change those surfaces too.
   */
  font?: string;
  /** Shared UI border radius, such as `8px`. */
  radius?: string;
  /** Shared UI box shadow. */
  shadow?: string;
  /** Semantic colors shared by SuperDoc UI components. */
  colors?: ThemeColors;
  /** Component-specific overrides, such as `{ '--sd-ui-toolbar-bg': '#f8fafc' }`. */
  vars?: ThemeVariableOverrides;
}

/** CSS generated by {@link buildTheme}. */
export interface ThemeResult {
  /** Class that activates the generated theme. */
  className: string;
  /** CSS rule containing the generated SuperDoc variables. */
  css: string;
}

const COLORS_TO_VARS = {
  action: '--sd-ui-action',
  actionHover: '--sd-ui-action-hover',
  actionText: '--sd-ui-action-text',
  bg: '--sd-ui-bg',
  hoverBg: '--sd-ui-hover-bg',
  activeBg: '--sd-ui-active-bg',
  disabledBg: '--sd-ui-disabled-bg',
  text: '--sd-ui-text',
  textMuted: '--sd-ui-text-muted',
  textDisabled: '--sd-ui-text-disabled',
  border: '--sd-ui-border',
} as const satisfies Record<keyof ThemeColors, `--sd-${string}`>;

let themeCounter = 0;

function generateTheme(config: ThemeConfig): ThemeResult {
  const { name, font, radius, shadow, colors, vars } = config;
  const safeName = name ? name.replace(/[^a-zA-Z0-9-_]/g, '-') : null;
  const className = `sd-theme-${safeName || `custom-${++themeCounter}`}`;

  const declarations: string[] = [];

  if (colors) {
    for (const [key, value] of Object.entries(colors)) {
      if (value == null) continue;
      const varName = COLORS_TO_VARS[key as keyof ThemeColors];
      if (varName) {
        declarations.push(`  ${varName}: ${value};`);
      }
    }
  }

  if (font != null) declarations.push(`  --sd-ui-font-family: ${font};`);
  if (radius != null) declarations.push(`  --sd-ui-radius: ${radius};`);
  if (shadow != null) declarations.push(`  --sd-ui-shadow: ${shadow};`);

  if (vars) {
    for (const [varName, value] of Object.entries(vars)) {
      if (value == null) continue;
      declarations.push(`  ${varName}: ${value};`);
    }
  }

  const css = declarations.length > 0 ? `.${className} {\n${declarations.join('\n')}\n}` : '';

  return { className, css };
}

/**
 * Inject a theme's CSS into the document as a `<style>` element.
 * Idempotent — re-calling with the same className updates the existing element.
 * No-op when `document` is not available (SSR).
 */
function injectThemeStyle(className: string, css: string): void {
  if (typeof document === 'undefined' || !css) return;
  let style = document.querySelector(`[data-sd-theme="${className}"]`);
  if (!style) {
    style = document.createElement('style');
    style.setAttribute('data-sd-theme', className);
    document.head.appendChild(style);
  }
  style.textContent = css;
}

/**
 * Create a SuperDoc theme from a config object.
 *
 * Returns a CSS class name. Apply it to `<html>` to activate the theme.
 * The style element is injected into the document automatically.
 *
 * For strict CSP environments that require a nonce, use {@link buildTheme} instead
 * and inject the CSS yourself with the appropriate nonce attribute.
 *
 * @example
 * ```ts
 * import { createTheme } from 'superdoc';
 *
 * const theme = createTheme({
 *   colors: { action: '#6366f1', bg: '#ffffff', text: '#1e293b' },
 *   font: 'Inter, sans-serif',
 *   vars: { '--sd-ui-toolbar-bg': '#f8fafc' },
 * });
 *
 * document.documentElement.classList.add(theme);
 * ```
 */
export function createTheme(config: ThemeConfig): string {
  const { className, css } = generateTheme(config);
  injectThemeStyle(className, css);
  return className;
}

/**
 * Build a SuperDoc theme and return both the class name and raw CSS.
 * This function does not access the DOM. Use it for server rendering or when
 * your application controls style injection, such as with a CSP nonce.
 *
 * @example
 * ```ts
 * import { buildTheme } from 'superdoc';
 *
 * const { className, css } = buildTheme({
 *   colors: { action: '#6366f1', bg: '#ffffff', text: '#1e293b' },
 * });
 *
 * const html = `<html class="${className}"><head><style>${css}</style></head>...</html>`;
 * ```
 */
export function buildTheme(config: ThemeConfig): ThemeResult {
  return generateTheme(config);
}
